### ISSUE TITLE
In Location object, move "crs" one level up

### ISSUE THREAD

**Issue by stefhummel** [DigitaleDeltaOrg/dd-api-spec#4]
Even though the crs has been removed from the GeoJSON specs, the DD-API still has it, to let systems be able to specify the coordinatie-system in case it is not wgs84.
However, we have put it on the wrong level (it should be on top level, not in "properties"

**Comment by gidthup** [comment]
Based on email exchange in December 2018 (Stef, Geri, Jurgen) the old GeoJSON definition of the 'crs' element should not be used anymore in DD-API to prevent confusion. Within DD-API we need however a mechanism to differentiate between at least WGS84 and ERTS92. Therefore the decision is taken to add a new DD-specific location property named 'crsName'.   The values will be set according to INSPIRE (see https://inspire.ec.europa.eu/documents/Data_Specifications/INSPIRE_Specification_CRS_v3.0.pdf) 

Although crsName is best defined at top level (same level as the coordinates themselves), it will be added inside the 'properties'  group  where the also other DD-specific attributes are defined.
As GeoJSON uses WGS84 as standard coordinate reference the crsName is optional and is only needed in case a different coordinate-system than WGS84 is used.

**Comment by stefhummel** [comment]
After some additional discussion indeed it has been decided that we:
- will remove GeoJSON's previous crs-object from the DD-API, because it is obsolete
- will add the crsName-member to the 'propertie' group.
This approach will:
- in many viewers automatically provide the end user with information on the crs in case it is not wgs84
- not conflict with GeoJSON-specs in case GeoJSON reintroduces a crs-spec. (they will  not do it on 'properties' level)
- lead to the least work in the existing 1.0 and 2.0 implementaties.

**Comment by stefhummel** [comment]
Specs have been adjusted according to discussion outcome.
